;This is used for generating musical notes from the system . 
(load "load")
(load "load-amb")
(init)

; (define (displaym label . things) 
;   (define should-display #t)
;   (define (internal)
;     (newline)
;     (display (string label ": "))
;     (if (> (length things) 1)
;       (for-each (lambda (thing)
;         (newline)
;         (display "    ")
;         (display thing)
;         )
;         things
;       )
;       (if (not (null? things)) (display (car things)))
;     )
;   )
;   (if should-display (internal) (display ""))
; )
(define (require p)
  (if (not p) (amb)))

(define (distinct l)
  (cond ((null? l) true)
  ((null? (cdr l)) true)
  ((member (car l) (cdr l)) false)
  (else (distinct (cdr l)))))


(define (parallel-octave? note1 note2)
  (display "val: ")
  (display note1)
  (newline)
  (display "get-cent: ")
  (display (get-cent (create-note note1 .25)))
  (newline)
  (display "get-cent: ")
  (display (get-cent (create-note note2 .25)))
  (newline)
  (newline)

  (= (abs (- 
    (get-cent (create-note note1 .25))
    (get-cent (create-note note2 .25)))) 
  1200))

(define (no-parallel-octaves l)
  (display "parallel")
  (cond ((null? l) true)
  ((null? (cdr l)) true)
  ((parallel-octave? (car l) (cadr l)) false)
  (else (no-parallel-octaves (cdr l)))))

(define (multiple-dwelling)
  (let ((fletcher (amb 1 2 3 4 5)))
      (require (not (= fletcher 5)))
      (require (not (= fletcher 1)))
      (let ((cooper (amb 1 2 3 4 5)))
        (require (not (= (abs (- fletcher cooper)) 1)))
        (require (not (= cooper 1)))
        (require (distinct (list fletcher cooper)))
        (let ((miller (amb 1 2 3 4 5)))
          (require (> miller cooper))
          (require (distinct (list fletcher cooper miller)))
          (let ((smith (amb 1 2 3 4 5)))
            (require (not (= (abs (- smith fletcher)) 1)))
            (require (distinct (list fletcher cooper miller smith)))
            (let ((baker (amb 1 2 3 4 5)))
              (require (not (= baker 5)))
              (require (distinct (list fletcher cooper miller smith baker)))
              (list (list 'baker baker)
                    (list 'cooper cooper)
                    (list 'fletcher fletcher)
                    (list 'miller miller)
                    (list 'smith smith))))
            )
          )
        )
      )
(multiple-dwelling)

(define amb-notes
  (lambda()
    (amb "c5" "c6" "c4" "e3")))

(define (gen-notes num l)
  (let 
    (
      (note1 (amb-notes))
      (note2 (amb-notes))
    )
    (require (distinct (list note1 note2)))
    (require (no-parallel-octaves (list note1 note2)))
    (list (list 'note1 note1) (list 'note2 note2))
  )
)

(gen-notes 5 '(3 0))