(define (displaym label . things) 
  (define should-display #t)
  (define (internal)
    (newline)
    (display (string label ": "))
    (if (> (length things) 1)
      (for-each (lambda (thing)
        (newline)
        (display "\t")
        (display thing)
        )
        things
      )
      (display (car things))
    )
  )
  (if should-display (internal) (display ""))
)